### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by ysdxj** [yz1639/FscanOutputBeautify#1]
```
Traceback (most recent call last):
  File "FscanOutput_v2.2.py", line 206, in <module>
    FscanBeautify(sys.argv[1]).run()
  File "FscanOutput_v2.2.py", line 197, in run
    self.parserData()
  File "FscanOutput_v2.2.py", line 113, in parserData
    "Port": int(port),
ValueError: invalid literal for int() with base 10: 'anonymous '
```

**Comment by yz1639** [comment]
方便 发一份脱敏源文件吗

**Comment by ysdxj** [comment]
文件较大，不太好脱敏
这是报错关键字部分
```
[+] ftp 10.1.1.1:21:anonymous 
   [->]soa
   [->]sums
[+] ftp 10.2.2.2:21:ftp 
   [->]disk-0
   [->]nfs
[+] ftp 10.3.3.3:21:admin 123
```

**Comment by yz1639** [comment]
你的fscan 版本是多少

**Comment by ysdxj** [comment]
fscan version: 1.8.3

**Comment by yz1639** [comment]
感谢反馈 v1.1版已上传 再试试看

**Comment by ysdxj** [comment]
有新的报错了，这是相关报错及fscan输出报错部分
```
Traceback (most recent call last):
  File "FscanOutputBeautify.py", line 209, in <module>
    FscanBeautify(sys.argv[1]).run()
  File "FscanOutputBeautify.py", line 200, in run
    self.parserData()
  File "\FscanOutputBeautify.py", line 116, in parserData
    "Port": int(port),
ValueError: invalid literal for int() with base 10: 'root 123456'
```
```
[+] SSH 10.1.1.1:22:root 123456
[+] mysql 10.2.2.2:3306:root 123456
```

**Comment by yz1639** [comment]
已上传v1.0.2 再试试看

**Comment by ysdxj** [comment]
新的报错信息
```
Traceback (most recent call last):
  File "FscanOutputBeautify_v1.0.2.py", line 215, in <module>
    FscanBeautify(sys.argv[1]).run()
  File "FscanOutputBeautify_v1.0.2.py", line 206, in run
    self.parserData()
  File "FscanOutputBeautify_v1.0.2.py", line 141, in parserData
    port = (rd_all[0].split(":"))[2]
IndexError: list index out of range
```

**Comment by yz1639** [comment]
这个应该是redis的报错，方便脱敏一下redis的部分给我吗

**Comment by ysdxj** [comment]
这是redis相关的信息
```
[+] Redis 10.1.154.35:6379 unauthorized file:/data/dump.rdb
[+] Redis 10.1.154.168:6379 123456 file:/usr/local/redis/bin/dump.rdb
[+] Redis 10.1.22.198:6379 unauthorized file:C:\Users\cn-xxxxxx\Documents\���\Redis-x64-3.0.504/dump.rdb
[+] Redis 10.1.22.178:6379 unauthorized file:C:\Program Files\Redis/dump.rdb
[+] Redis 10.1.214.71:6379 unauthorized file:/home/mcduser/redis-4.0.10/dump.rdb
[+] Redis 10.1.50.28:6379 123456
[+] Redis 10.1.23.203:6379 123456 file:D:\redis/dump.rdb
[+] Redis 10.1.214.103:6379 like can write /root/.ssh/
[+] Redis 10.1.214.103:6379 like can write /var/spool/cron/
[+] Redis 10.1.63.105:6379 123456 file:/data/dump.rdb
[+] Redis 10.1.158.209:6379 1qaz!QAZ file:/data/redis/data/dump.rdb
```

**Comment by yz1639** [comment]
好了师傅  试试1.0.3吧 如果后续还是有报错，方便加下您微信吗

**Comment by yz1639** [comment]
师傅是不是没开放搜索,没搜到

**Comment by ysdxj** [comment]
现在试试呢

**Comment by yz1639** [comment]
可以了，师傅可以吧微信删掉了
